# Generated by Django 3.2 on 2021-12-31 14:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Resim Kodu')),
                ('header', models.CharField(max_length=200, verbose_name='Başlık')),
                ('file_link', models.FileField(blank=True, null=True, upload_to='announcements', verbose_name='Resim')),
                ('isactive', models.BooleanField(default=False, verbose_name='Aktif')),
                ('subject', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
