# Generated by Django 3.2 on 2022-01-01 16:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signum', '0002_alter_picture_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Kod')),
                ('header', models.CharField(max_length=200, verbose_name='Başlık')),
                ('file_link', models.FileField(blank=True, null=True, upload_to='announcements', verbose_name='Resim')),
                ('isactive', models.BooleanField(default=False, verbose_name='Aktif')),
                ('subject', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
