# Generated by Django 3.2 on 2022-02-11 08:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200, verbose_name='Başlık')),
                ('text', models.TextField(max_length=4000, verbose_name='Duyuru Metni')),
                ('file_link', models.FileField(blank=True, null=True, upload_to='announcements', verbose_name='Resim')),
                ('isactive', models.BooleanField(default=False, verbose_name='Aktif')),
                ('rich_text', ckeditor.fields.RichTextField(verbose_name='Htm Metin')),
                ('show_rich_text', models.BooleanField(default=False, verbose_name='Tam Metni HTML Göster')),
            ],
        ),
    ]
