# Generated by Django 3.2 on 2022-02-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='İlk Yayın Tarihi'),
        ),
    ]
