# Generated by Django 3.2 on 2022-02-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_announcement_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=models.TextField(verbose_name='Duyuru Metni'),
        ),
    ]
