# Generated by Django 3.2 on 2022-02-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_alter_announcement_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='header',
            field=models.CharField(max_length=220, verbose_name='Başlık'),
        ),
    ]
